#!/usr/bin/env python3
"""Slice one still frame per species out of Battle Art's animated Gen 5 (Black/White)
atlases and write a gen1recomp mod asset tree plus data/sprites.lua.

usage: slice_sprites.py <battle-art-mod-dir> <species-source> <out-mod-dir> [--set=gen5]

<species-source> is either the engine's Crystal cache dir (…/crystal/data/generated,
its pokemon.lua gives the species ids) or a text file with one species id per line
(species_gen2.txt in this repo: no ROM or cache needed).
"""
import os, re, sys
from PIL import Image

args = [a for a in sys.argv[1:] if not a.startswith("--")]
SRC, CACHE, OUT = args[0], args[1], args[2]
SET = "gen5"
for a in sys.argv[1:]:
    if a.startswith("--set="): SET = a.split("=", 1)[1]

# Crystal id -> Battle Art table key where the spelling differs
ALIAS = {"MR__MIME": "MR_MIME", "FARFETCH_D": "FARFETCHD"}

def parse_table(path):
    """{KEY: {"front": {...}, "back": {...}}} from Battle Art's generated Lua tables."""
    t = open(path).read()
    out = {}
    for m in re.finditer(r'^\s{2}([A-Z_0-9]+) = \{(.*?)^\s{2}\},', t, re.S | re.M):
        key, body = m.group(1), m.group(2)
        rec = {}
        for side in ("front", "back"):
            sm = re.search(side + r' = \{ image = "([^"]+)", width = (\d+), height = (\d+), columns = (\d+), frames = (\d+)', body)
            if sm:
                rec[side] = {"image": sm.group(1), "w": int(sm.group(2)), "h": int(sm.group(3)),
                             "cols": int(sm.group(4)), "frames": int(sm.group(5))}
        out[key] = rec
    return out

normal = parse_table(os.path.join(SRC, "data", f"animated_battle_sprites_{SET}.lua"))
shiny = parse_table(os.path.join(SRC, "data", f"animated_battle_sprites_{SET}_shiny.lua"))
if os.path.isdir(CACHE):
    crystal = re.findall(r'^\s{2}([A-Z_0-9]+) = \{', open(os.path.join(CACHE, "pokemon.lua")).read(), re.M)
else:
    crystal = [l.strip() for l in open(CACHE) if l.strip() and not l.startswith("#")]

def frame0(rec):
    p = os.path.join(SRC, rec["image"])
    if not os.path.exists(p):
        # Unown ships one atlas per letter (unown-a.png ...); the table names the bare file
        alt = p[:-4] + "-a.png"
        if not os.path.exists(alt): return None
        p = alt
    im = Image.open(p).convert("RGBA")
    W, H = im.size
    rows = -(-rec["frames"] // rec["cols"])
    if W != rec["w"] * rec["cols"] or H != rec["h"] * rows:
        # layout mismatch: fall back to the first cell of the declared size if it fits
        if rec["w"] > W or rec["h"] > H: return None
    cell = im.crop((0, 0, rec["w"], rec["h"]))
    bbox = cell.getbbox()
    if not bbox: return None
    return cell.crop(bbox)

def scale_for(w, h, side):
    m = max(w, h)
    # keep some of Black/White's size relationships instead of normalising fully:
    # fronts land between ~44 and 56 px (the 7-tile enemy box is 56), backs ~38-48.
    if side == "front": target = 44 + 12 * min(1.0, m / 96)
    else: target = 38 + 10 * min(1.0, m / 96)
    return round(target / m, 4)

entries, missing, n = [], [], 0
for sp in crystal:
    key = ALIAS.get(sp, sp)
    rec, srec = normal.get(key, {}), shiny.get(key, {})
    fields = []
    for tag, side, table_rec in (("front", "front", rec), ("back", "back", rec),
                                 ("front_shiny", "front", srec), ("back_shiny", "back", srec)):
        r = table_rec.get(side)
        img = frame0(r) if r else None
        if img is None:
            missing.append(f"{sp}.{tag}")
            continue
        rel = f"battle/{tag.replace('_', '-')}/{sp}.png"
        dst = os.path.join(OUT, "assets", rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        img.save(dst, optimize=True)
        n += 1
        fields.append(f'    {tag} = {{ path = "{rel}", w = {img.width}, h = {img.height}, scale = {scale_for(img.width, img.height, side)} }},')
    if fields:
        entries.append(f"  {sp} = {{\n" + "\n".join(fields) + "\n  },")

os.makedirs(os.path.join(OUT, "data"), exist_ok=True)
with open(os.path.join(OUT, "data", "sprites.lua"), "w") as f:
    f.write(f"-- Generated by tools/slice_sprites.py from Battle Art's {SET} tables. Do not edit.\n")
    f.write("-- One still frame per species; scale = draw scale for the engine's battle pic box.\n")
    f.write("return {\n" + "\n".join(entries) + "\n}\n")
print(f"species: {len(crystal)} | pics written: {n} | missing: {len(missing)}")
if missing: print("missing:", missing[:20])
