#!/usr/bin/env python3
"""Write data/art.lua for CRYSTAL_TRAINER_ART from the sprites in assets/.
usage: build_data.py <mod-dir>   (expects assets/trainers/*.png and assets/player/*.png, 64x64)"""
import os, sys
from PIL import Image
M = sys.argv[1]
def recs(sub, box):
    out = []
    d = os.path.join(M, "assets", sub)
    for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if not f.endswith(".png"): continue
        im = Image.open(os.path.join(d, f))
        out.append(f'    {f[:-4]} = {{ path = "assets/{sub}/{f}", scale = {round(box / max(1, im.height), 4)} }},')
    return out
os.makedirs(os.path.join(M, "data"), exist_ok=True)
t, p = recs("trainers", 56), recs("player", 48)
open(os.path.join(M, "data", "art.lua"), "w").write("-- Generated by build_data.py. Do not edit.\nreturn {\n  trainers = {\n" + "\n".join(t) + "\n  },\n  player = {\n" + "\n".join(p) + "\n  },\n}\n")
print(len(t), "trainer records,", len(p), "player records")
