-- Crystal Battle Art: full-colour Gen 5 (Black/White) battle sprites for Gen 2.
--
-- The engine asks the pokemon.sprite hook for every battle pic with the side
-- it is resolving. This mod answers with its own still frame for the species
-- and marks it true-colour so the GBC palette pass leaves it alone. A replaced
-- static pic whose Crystal anim sheet is NOT replaced is held still by the
-- engine, so nothing else is needed for the pics to show.
--
-- Each pic's draw scale lives in data/sprites.lua (generated by
-- tools/slice_sprites.py) and is registered on battle_sprite_scales, which the
-- Gen 2 battle screen reads per image path.
local mod = ...

-- The sandbox hands a mod its own files as text; Lua's load turns the data
-- table back into a value (the same route Terrarium's data files take).
local function loadData(rel)
  local source = mod:read(rel)
  if not source then
    error(("CRYSTAL_BATTLE_ART: %s is missing -- reinstall the mod"):format(rel), 0)
  end
  local chunk, err = load(source, "@" .. tostring(mod.path) .. "/" .. rel)
  if not chunk then
    error(("CRYSTAL_BATTLE_ART: %s did not compile: %s"):format(rel, tostring(err)), 0)
  end
  return chunk()
end

local SPRITES = loadData("data/sprites.lua")

local resolved = {}   -- data path -> engine asset path
local function assetPath(rel)
  local hit = resolved[rel]
  if hit then return hit end
  local path = mod.assets:path("assets/" .. rel)
  resolved[rel] = path
  return path
end

-- Register every pic's scale up front: the record's path must equal the path
-- the hook returns, byte for byte.
local registered = 0
for species, rec in pairs(SPRITES) do
  for tag, pic in pairs(rec) do
    local path = assetPath(pic.path)
    if path then
      mod.content.battle_sprite_scales:register(
        "cba_" .. species .. "_" .. tag, { path = path, scale = pic.scale })
      registered = registered + 1
    end
  end
end
mod.log:info("Crystal Battle Art: %d battle pics registered", registered)

mod.hooks:wrap("pokemon.sprite", function(next, path, ctx)
  local out = next(path, ctx)
  if not (ctx and ctx.kind == "battle" and ctx.species) then return out end
  local rec = SPRITES[ctx.species]
  if not rec then return out end
  local side = ctx.side == "back" and "back" or "front"
  local pic = (ctx.shiny and rec[side .. "_shiny"]) or rec[side]
  if not pic then return out end
  local resolvedPath = assetPath(pic.path)
  if not resolvedPath then return out end
  ctx.trueColor = true
  return resolvedPath
end)
